use master
GO
IF NOT EXISTS(SELECT name FROM master.dbo.sysdatabases WHERE NAME = 'DBMATRICULAS')
CREATE DATABASE DBMATRICULAS

GO

USE DBMATRICULAS

GO

IF  NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'PERSONA')
CREATE TABLE PERSONA(
    IdPersona INT PRIMARY KEY IDENTITY(1,1),
    Nombres VARCHAR(100) NOT NULL,
    Apellidos VARCHAR(100) NOT NULL,
    Matricula VARCHAR(10) NOT NULL,
    FechaNacimiento DATETIME NOT NULL,
    UbicacionLatitud DECIMAL,
    UbicacionLongitud DECIMAL,
    UbicacionAltitud DECIMAL,
)

GO
