//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBMATRICULASEntities : DbContext
    {
        public DBMATRICULASEntities()
            : base("name=DBMATRICULASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PERSONA> PERSONA { get; set; }
    
        public virtual ObjectResult<stp_findAll_Result> stp_findAll()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_findAll_Result>("stp_findAll");
        }
    
        public virtual ObjectResult<stp_findByMatricula_Result> stp_findByMatricula(string matricula)
        {
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<stp_findByMatricula_Result>("stp_findByMatricula", matriculaParameter);
        }
    
        public virtual int stp_insert(string nombres, string apellidos, string matricula, Nullable<System.DateTime> fechaNAcimiento, Nullable<decimal> ubicacionLatitud, Nullable<decimal> ubicacionLongitud, Nullable<decimal> ubicacionAltitud)
        {
            var nombresParameter = nombres != null ?
                new ObjectParameter("nombres", nombres) :
                new ObjectParameter("nombres", typeof(string));
    
            var apellidosParameter = apellidos != null ?
                new ObjectParameter("apellidos", apellidos) :
                new ObjectParameter("apellidos", typeof(string));
    
            var matriculaParameter = matricula != null ?
                new ObjectParameter("matricula", matricula) :
                new ObjectParameter("matricula", typeof(string));
    
            var fechaNAcimientoParameter = fechaNAcimiento.HasValue ?
                new ObjectParameter("fechaNAcimiento", fechaNAcimiento) :
                new ObjectParameter("fechaNAcimiento", typeof(System.DateTime));
    
            var ubicacionLatitudParameter = ubicacionLatitud.HasValue ?
                new ObjectParameter("ubicacionLatitud", ubicacionLatitud) :
                new ObjectParameter("ubicacionLatitud", typeof(decimal));
    
            var ubicacionLongitudParameter = ubicacionLongitud.HasValue ?
                new ObjectParameter("ubicacionLongitud", ubicacionLongitud) :
                new ObjectParameter("ubicacionLongitud", typeof(decimal));
    
            var ubicacionAltitudParameter = ubicacionAltitud.HasValue ?
                new ObjectParameter("ubicacionAltitud", ubicacionAltitud) :
                new ObjectParameter("ubicacionAltitud", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("stp_insert", nombresParameter, apellidosParameter, matriculaParameter, fechaNAcimientoParameter, ubicacionLatitudParameter, ubicacionLongitudParameter, ubicacionAltitudParameter);
        }
    }
}
